name: Deploy Firebase Backend

on:
    push:
        branches:
            - main

jobs: 
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Firebase CLI
              run: npm install -g firebase-tools

            - name: Authenticate with Firebase
              env:
                FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
              run: echo "$FIREBASE_SERVICE_ACCOUNT" > firebase-key.json
            
            - name: Deploy Firebase Service
              run: |
                firebase use --add YOUR_FIREBASE_PROJECT_ID
                firebase deploy --token "$GOOGLE_APPLICATION_CREDENTIALS"
              env:
                GOOGLE_APPLICATION_CREDENTIALS: ./firebase-key.json